<?php

namespace MailPoetVendor;

// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInit89c59619e822f23f6351f7c38e75c79c::getLoader();
